const freelancers = [
    {
      id: 1,
      name: "Elias Baloyi",
      title: "Web Designer",
      company: "DesignHub",
      rate: "R1200/hr",
      image: "https://randomuser.me/api/portraits/women/44.jpg",
      skills: ["Figma", "Adobe XD", "HTML/CSS", "UI/UX"],
      location: "Limpopo, Tzaneen",
      experience: "8 years",
      bio: "Creative web designer with 8 years of experience creating beautiful, user-friendly interfaces. Specialized in responsive design and UX principles."
    },
    {
      id: 2,
      name: "Leon Maputla",
      title: "Full Stack Developer",
      company: "TechSolutions",
      rate: "R1150/hr",
      image: "https://randomuser.me/api/portraits/men/32.jpg",
      skills: ["JavaScript", "React", "Node.js"],
      location: "Limpopo, Polokwane",
      experience: "10 years",
      bio: "Full-stack developer passionate about building scalable web applications."
    },
    {
      id: 3,
      name: "Ezra Nkontwana",
      title: "UX Designer",
      company: "DigitalSA",
      rate: "R800/hr",
      image: "https://randomuser.me/api/portraits/women/63.jpg",
      skills: ["User Research", "Wireframing", "Prototyping", "Adobe Creative Suite"],
      location: "Johannesburg, South Africa",
      experience: "5 years",
      bio: "Johannesburg-based UX designer passionate about creating inclusive digital experiences for African users."
    },
    {
      id: 4,
      name: "Phetho Nemavhola",
      title: "Graphic Designer",
      company: "Creative Afrika",
      rate: "R650/hr",
      image: "https://randomuser.me/api/portraits/women/25.jpg",
      skills: ["Branding", "Illustration", "Print Design", "Packaging"],
      location: "Cape Town, South Africa",
      experience: "4 years",
      bio: "Award-winning graphic designer specializing in brand identities for African startups and NGOs."
    },
    {
      id: 5,
      name: "Lerato Khumalo",
      title: "Frontend Developer",
      company: "TechAfrica",
      rate: "R950/hr",
      image: "https://randomuser.me/api/portraits/women/68.jpg",
      skills: ["React", "Vue.js", "TypeScript", "CSS"],
      location: "Durban, South Africa",
      experience: "6 years",
      bio: "Specializing in building performant web applications for the African market."
    },
    {
      id: 6,
      name: "Nsovo Nkuna",
      title: "DevOps Engineer",
      company: "CloudAfrica",
      rate: "R1100/hr",
      image: "https://randomuser.me/api/portraits/men/22.jpg",
      skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
      location: "Pretoria, South Africa",
      experience: "7 years",
      bio: "Helping African businesses scale their infrastructure with cloud technologies."
    },
    {
      id: 7,
      name: "Khutso Mashapu",
      title: "Mobile Developer",
      company: "AppFactory",
      rate: "R900/hr",
      image: "https://randomuser.me/api/portraits/men/45.jpg",
      skills: ["Flutter", "React Native", "Firebase", "Android"],
      location: "Port Elizabeth, South Africa",
      experience: "5 years",
      bio: "Building cross-platform mobile apps that solve real African problems."
    },
    {
      id: 8,
      name: "Vhulenda Mashamba",
      title: "Data Scientist",
      company: "DataFirst",
      rate: "R1200/hr",
      image: "https://randomuser.me/api/portraits/men/87.jpg",
      skills: ["Python", "Machine Learning", "SQL", "TensorFlow"],
      location: "Bloemfontein, South Africa",
      experience: "8 years",
      bio: "Applying data science to solve unique challenges in the Southern African context."
    },
    {
      id: 9,
      name: "Paballo Lipopo",
      title: "Backend Developer",
      company: "CodeZA",
      rate: "R850/hr",
      image: "https://randomuser.me/api/portraits/men/33.jpg",
      skills: ["Node.js", "Python", "MongoDB", "API Design"],
      location: "Soweto, South Africa",
      experience: "4 years",
      bio: "Specializing in building robust backend systems for high-growth startups."
    },
    {
      id: 10,
      name: "Thando Nkosi",
      title: "Digital Marketer",
      company: "GrowthAfrica",
      rate: "R750/hr",
      image: "https://randomuser.me/api/portraits/men/91.jpg",
      skills: ["SEO", "Social Media", "Content Strategy", "Google Ads"],
      location: "Polokwane, South Africa",
      experience: "5 years",
      bio: "Helping African brands grow their digital presence through data-driven marketing."
    },
    {
      id: 11,
      name: "Siyabonga Zulu",
      title: "Cybersecurity Specialist",
      company: "SecureZA",
      rate: "R1300/hr",
      image: "https://randomuser.me/api/portraits/men/56.jpg",
      skills: ["Ethical Hacking", "Pen Testing", "Network Security", "GDPR"],
      location: "Nelspruit, South Africa",
      experience: "9 years",
      bio: "Protecting African businesses from evolving cyber threats with cutting-edge security solutions."
    }
  ];