name: Node.js CI

on:
  push:
    branches:
      - main  # Trigger action on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger action on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # This is the operating system for the runner
    
    steps:
    # Step 1: Check out your code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # Specify the Node.js version (change to your required version)

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run tests
    - name: Run tests
      run: npm test -- --coverage  # Run your tests with coverage

    # Optional: Upload test coverage results to GitHub
    - name: Upload coverage results
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov-report/index.html
