name: coverage

on:
  push:
    branches: Testing
  pull_request:
    branches: Testing

jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci # Better for CI environments if using package-lock.json

      - name: Set Permissions
        run: chmod +x node_modules/.bin/jest

      - name: Run tests with coverage
        run: npm run test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }} # Optional for public repos
