name: Test with Codecov
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: FreeLancer-Management

      - name: Run tests with coverage
        run: npm test -- --coverage
        working-directory: FreeLancer-Management

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./FreeLancer-Management/coverage/coverage-final.json
          flags: javascript
